### ISSUE TITLE
Update to support Flutter 3

### ISSUE THREAD

**Issue by giolaq** [dooboolab-community/flutter_inapp_purchase#395]
Is there any plan to update the plugin to Flutter 3?

**Comment by eEQK** [comment]
is there anything that stops you from using this plugin with flutter 3?

**Comment by giolaq** [comment]
Plugin is working with Flutter 3. Maybe we could update the sample to Flutter 3?

**Comment by temelyazilim** [comment]
FlutterInappPurchase.instance.getProducts doesn't work after flutter 3.7.7 update.

**Comment by meowofficial** [comment]
@temelyazilim In my case the issue arised after setting base country for upcoming Apple price change. Previously working TestFlight build stopped work, but the same build in production works as expected. Similar issue by developer not using this plugin https://community.revenuecat.com/general-questions-7/i-can-t-get-iap-only-subscriptions-2667.

**Comment by temelyazilim** [comment]
ios working but android doesn't show prices.

**Comment by temelyazilim** [comment]
> @temelyazilim In my case the issue arised after setting base country for upcoming Apple price change. Previously working TestFlight build stopped work, but the same build in production works as expected. Similar issue by developer not using this plugin https://community.revenuecat.com/general-questions-7/i-can-t-get-iap-only-subscriptions-2667.

flutter 3.7.7

<img width="853" alt="android" src="https://user-images.githubusercontent.com/73512123/224654629-ddd53086-112e-4140-89bb-9c65d32d12c9.png">
not working

<img width="842" alt="ios" src="https://user-images.githubusercontent.com/73512123/224654656-42657432-5941-4c27-a593-c317e593505e.png">
working

**Comment by meowofficial** [comment]
@temelyazilim Looks like a different issue comparing to mine. Instead of non-consumable products I get an empty list. I don't have consumable products. You could try to downgrade the `flutter_inapp_purchase` version, last version brought some changes to android billing.

**Comment by eEQK** [comment]
@temelyazilim could it be related to google releasing play billing 5.1 library? are you running the latest version (5.4.0) of `flutter_inapp_purchase`?

**Comment by temelyazilim** [comment]
yes, we are using 5.4.0

Karol ***@***.***>, 13 Mar 2023 Pzt, 13:10 tarihinde şunu
yazdı:

**Comment by temelyazilim** [comment]
we downgrade to flutter_inapp_purchase: 5.2.0

now working again. what should we do to use 5.4.0? ios working but android not.

**Comment by renolation** [comment]
im using 5.2.0 and the price now show in android

**Comment by hyochan** [comment]
@renolation @temelyazilim The major changes in `5.4.0` in android is that billing client is upgraded to `5.1`. This is done in #392 by @SamBergeron.

If possible could @SamBergeron join this conversation?

**Comment by renolation** [comment]
> @renolation @temelyazilim The major changes in `5.4.0` in android is that billing client is upgraded to `5.1`. This is done in #392 by @SamBergeron.
> 
> If possible could @SamBergeron join this conversation?

in android 13 and plugin 5.4.0 i got this Please fetch setObfuscatedAccountIdproducts first by calling getItems. but when i get items, it gets enough

**Comment by offline-first** [comment]
Here is a fix for the one time purchases (price is null)
here is my pr: https://github.com/dooboolab-community/flutter_inapp_purchase/pull/435
