### ISSUE TITLE
instance.getProducts Obselete  Unhandled Exception: PlatformException(E_UNKNOWN, An unknown

### ISSUE THREAD

**Issue by XeroDays** [dooboolab-community/flutter_inapp_purchase#415]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/38852291/227566341-b4d4ec39-57fc-4476-ad9c-767ac004dda5.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/38852291/227566492-fbf40d01-afc0-482b-91c0-580c6ccdb7b0.png">

**Version 5.3.1** is no longer working with the IOs.

When i trgger the line 
```
 List<IAPItem> items =
        await FlutterInappPurchase.instance.getProducts(_productLists);
```

this causes me the above errors.

**Comment by vini2001** [comment]
I've been experiencing the same issue

**Comment by XeroDays** [comment]
What I did was I shifted back to the original Flutter In-App Purchases  [in_app_purchase](https://pub.dev/packages/in_app_purchase) which sorted out the issue as Plan B.
