### ISSUE TITLE
Unable to buy consumable product getting crashed

### ISSUE THREAD

**Issue by pabbathiharish** [dooboolab-community/flutter_inapp_purchase#426]
### Steps to reproduce the behavior

Add any InApp Product, and getProducts, the select any one product getting below Error.

E/flutter ( 7319): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(InappPurchasePlugin, buyItemByType, null, null)
E/flutter ( 7319): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 7319): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter ( 7319): <asynchronous suspension>
E/flutter ( 7319): #2      FlutterInappPurchase.requestPurchase (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:278:14)
E/flutter ( 7319): <asynchronous suspension>

**Comment by kemalserbet** [comment]
I've experienced the same problem. Is there any solution?

**Comment by LatCui** [comment]
I have the same problem!

**Comment by kemalserbet** [comment]
I was using "_flutter_inapp_purchase: ^5.0.2_". Can you please change it with "_flutter_inapp_purchase: 5.3.0_" and try again? Please don't forget to remove "**^**".

**Comment by moodstubos** [comment]
This seems to be the same issue: https://github.com/dooboolab-community/flutter_inapp_purchase/issues/430

Unforunately it was closed. The posted workaround from @mdusaama0 worked for me.

**Comment by meowofficial** [comment]
Just preventing the issue from closing. Products in the last version `5.4.2` are still unusable on android.
