### ISSUE TITLE
Unhandled Exception: PlatformException(InappPurchasePlugin, buyItemByType, null, null)

### ISSUE THREAD

**Issue by virajtalaviya** [dooboolab-community/flutter_inapp_purchase#430]
### Version of flutter_inapp_purchase
5.4.1

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
should show more details of the error

### Actual behavior
showing this error while requesting purchase with no more specifications why it is coming up

### Tested environment (Emulator? Real Device?)
Real device

**Comment by virajtalaviya** [comment]
Version of flutter_inapp_purchase -> 5.4.1
Platforms you faced the error (IOS or Android or both?) -> Android
Expected behavior -> should show more details of the error 
Actual behavior -> showing this error while requesting purchase with no more specifications why it is coming up
Tested environment (Emulator? Real Device?) -> Real device
Steps to reproduce the behavior

**Comment by SuperTizzyGod** [comment]
![image](https://github.com/dooboolab-community/flutter_inapp_purchase/assets/31981086/79a913a6-a089-42bd-81f6-acacb7add36c)
because inapp product detail:selectedProductDetails.subscriptionOfferDetails is null

**Comment by mdusaama0** [comment]
> ![image](https://user-images.githubusercontent.com/31981086/240508332-79a913a6-a089-42bd-81f6-acacb7add36c.png) because inapp product detail:selectedProductDetails.subscriptionOfferDetails is null

How to solve this?

**Comment by mdusaama0** [comment]
> ### Version of flutter_inapp_purchase
> 5.4.1
> 
> ### Platforms you faced the error (IOS or Android or both?)
> Android
> 
> ### Expected behavior
> should show more details of the error
> 
> ### Actual behavior
> showing this error while requesting purchase with no more specifications why it is coming up
> 
> ### Tested environment (Emulator? Real Device?)
> Real device

Hey I got the same error.
I solved it by these steps.

- go to native kotlin code of the plugin.
- goto this file path: flutter_inapp_purchase-5.4.1/android/src/main/kotlin/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.kt
- go to private fun buyProduct() method in the file
- go to line number 514
- remove below code from line 514 to 522
`if (offerToken == null) {
                offerToken = selectedProductDetails.subscriptionOfferDetails!![0].offerToken
            }

            val productDetailsParamsList =
            listOf(ProductDetailsParams.newBuilder()
                .setProductDetails(selectedProductDetails)
                .setOfferToken(offerToken)
                .build())`
- replace the code with this code.
`if (offerToken == null) {
                offerToken = selectedProductDetails.subscriptionOfferDetails?.get(0)?.offerToken
            }

            val productDetailsParamsList =
            listOf(
                if(offerToken == null) ProductDetailsParams.newBuilder()
                .setProductDetails(selectedProductDetails)
                .build()
                else ProductDetailsParams.newBuilder()
                     .setProductDetails(selectedProductDetails)
                     .setOfferToken(offerToken)
                     .build()
            )`
- restart the app and boom.

**Comment by gkovac42** [comment]
It would be nice if this fix made it into the official release...

**Comment by moodstubos** [comment]
@virajtalaviya 
Why did you close this issue? It doesn't seem to be fixed yet.

**Comment by deakjahn** [comment]
The PR was sent in April... https://github.com/dooboolab-community/flutter_inapp_purchase/pull/423
