### ISSUE TITLE
Subscription Auto-Canceling Issue

### ISSUE THREAD

**Issue by mustakimpawle** [dooboolab-community/flutter_inapp_purchase#442]
Plugin Name: flutter_inapp_purchase

Version: 5.4.2

Platform : Android

Expected behavior: Subscription should not get auto cancel after purchased.

Tested environment : Real Device

Flutter Doctor: 
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6.5 21G531 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!

Attachment: 
![error](https://github.com/dooboolab-community/flutter_inapp_purchase/assets/39689721/ef73be80-f058-44d9-953a-d31fd68b7cad)

**Comment by nexoftcengizhan** [comment]
Did you find any solution? @mustakimpawle

**Comment by BhagyeshAgiles** [comment]
@mustakimpawle  @nexoftcengizhan  Try this
FlutterInappPurchase.purchaseUpdated.listen((productItem) async {
  if (productItem.purchaseStateAndroid == PurchaseState.purchased) {
    purchaseTokens.value = productItem.purchaseToken ?? "";
    await FlutterInappPurchase.instance.finishTransaction(productItem);
    await FlutterInappPurchase.instance.acknowledgePurchaseAndroid(productItem.purchaseToken ?? '');
    alreadySubscribed(objOfPurchasedItem: productItem);
  } else {
    if (kDebugMode) {
      print("Else purchase error: ${productItem.purchaseStateAndroid}");
    }
  }
});
This code listens for purchase updates and, when a purchase is successful (PurchaseState.purchased), it performs the following actions:

Stores the purchase token in the purchaseTokens.value variable.
Calls finishTransaction to complete the purchase transaction.
Calls acknowledgePurchaseAndroid to acknowledge the purchase on the Android side.
Calls the alreadySubscribed function, passing the purchased item (productItem) to handle further processing.
If the purchase state is not "purchased," it prints an error message to the console (if in debug mode).

Make sure to include this code within the appropriate part of your Flutter app where you handle in-app purchases and adjust it as needed to fit your specific use case.

**Comment by RomanSoviak** [comment]
Did you find the solution?

**Comment by DagmawiN** [comment]
I am facing the same thing with this issue.

In more detail, this is what happens:
A user finishes subscribing and the purchase receipt is validated, completed and the purchase detail (i.e. orderId) is stored for later use.  
Function in use:  _inAppPurchase.finishTransaction(productItem);

After that, the user can use the subscription for a while but later on, maybe the app has restarted or the user reinstalled the app,  in the app it checks whether the subscription is active using the orderId that was stored with the help of either one of these functions:
      1. _inAppPurchase.getAvailablePurchases()
      2. _inAppPurchase.checkSubscribed(sku: orderId)
 
And both functions detect, after sometime, as an inactive subscription even if the subscription is still going in the playstore subscriptions.

**Comment by RomanSoviak** [comment]
Any updates?
