### ISSUE TITLE
How to obtain free trial period on android after migration on android billing v5? 

### ISSUE THREAD

**Issue by nickzutobicom** [dooboolab-community/flutter_inapp_purchase#444]
### Version of flutter_inapp_purchase
5.4.2

### Platforms you faced the error (IOS or Android or both?)
android

### Expected behavior
I should be able to access IAPItem.freeTrialPeriodAndroid or similar api

### Actual behavior
i'm unable to find expected field, getter or helper method

### Tested environment (Emulator? Real Device?)
android device

### Steps to reproduce the behavior
Try to migrate code using IAPItem.freeTrialPeriodAndroid from 5.3.1 to 5.4.2

**Comment by nickzutobicom** [comment]
Closing it as won't fix

**Comment by RomanSoviak** [comment]
@nickzutobicom I cannot find it, could you please show the detailed code?

<img width="265" alt="Screenshot 2024-02-11 at 00 04 47" src="https://github.com/dooboolab-community/flutter_inapp_purchase/assets/26696190/4d6b7bc7-7eb6-40bc-b940-5fb7bece9160">
