### ISSUE TITLE
need upgrade its dependency http0.13.4 to http 1.0.0 

### ISSUE THREAD

**Issue by stdroom** [dooboolab-community/flutter_inapp_purchase#446]
### Because image_cropper_platform_interface 5.0.0 depends on http ^1.0.0 and no versions of image_cropper_platform_interface match >5.0.0 <6.0.0, image_cropper_platform_interface ^5.0.0 requires http ^1.0.0.
And because flutter_inapp_purchase >=5.0.4 depends on http ^0.13.4, flutter_inapp_purchase >=5.0.4 is incompatible with image_cropper_platform_interface ^5.0.0.
And because image_cropper 5.0.0 depends on image_cropper_platform_interface ^5.0.0 and no versions of image_cropper match >5.0.0 <6.0.0, flutter_inapp_purchase >=5.0.4 is incompatible with image_cropper ^5.0.0.
So, because money_make depends on both image_cropper ^5.0.0 and flutter_inapp_purchase ^5.4.2, version solving failed.

Hello when i upgrade flutter to 3.13 ,found that this library need upgrade its dependency http0.13.4 to http 1.0.0

**Comment by luckyrat** [comment]
Have you tried putting this in your pubspec.yaml?

```
dependency_overrides:
  http: 1.1.0
```

This works around the dependency mismatch for me but it'll be a while before I can verify that there are no incompatible APIs being used from any of the various dependencies, and that will vary based on which libraries you depend on so you'll be out of luck if flutter_inapp_purchase uses some http API that has been broken in v1.0.0+ and image_cropper_platform_interface can't work with a forced override to an older version (i.e. 0.13.4)

**Comment by archie20** [comment]
@stdroom A new version was released a week ago that upgrades http to 1.0.0
