### ISSUE TITLE
Upgrade Android Billing Library

### ISSUE THREAD

**Issue by daviinjuguna** [dooboolab-community/flutter_inapp_purchase#452]
### Version of flutter_inapp_purchase
flutter_inapp_purchase 5.4.2 

### Platforms you faced the error (IOS or Android or both?)
Android platform, Target SDK android 14

### Expected behavior
The app is uploaded to play store successfully.
### Actual behavior
The app refuse to be uploaded to playstore.
It shows the following error:-
This app targets Android 14 or above, and your current Play Billing Library version doesn't support Android 14. To target the latest Android version, please update your PBL version to either 5.2.1, or 6.0.1 and above.
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
Install the latest package and upload the app to play store

**Comment by vipvijayan** [comment]
Hi Team,

Any update on this?

Thanks

**Comment by flappe8888** [comment]
There is information on the web that an update is required if the app targets Android 14 or later.
https://developer.android.com/google/play/billing/migrate-gpblv6?hl=en

**Comment by xalikoutis** [comment]
Hi people any update on this?

**Comment by basemkhirat** [comment]
any updates on this?
