### ISSUE TITLE
SDK存在com.dooboolab .fluterinapppurchaseio.futterembeddingjio.futer plugins获取安装列表的行为，

### ISSUE THREAD

**Issue by pen110** [dooboolab-community/flutter_inapp_purchase#463]
### Version of flutter_inapp_purchase
flutter_inapp_purchase: ^5.4.1

### Platforms you faced the error (IOS or Android or both?)
iOS

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
APP以隐私政策弹窗的形式向用户明示收集使用规则，未经用户同意，存在收集安装列表的行为APP向用户明示SDK的收集使用规规则，未经用户同意，SDK存在com.dooboolab .fluterinapppurchaseio.futterembeddingjio.futer plugins获取安装列表的行为，
在安装的时候，就被提示获取安装列表的行为，如何规避掉这个

**Comment by supermebing** [comment]
同样遇到 xiaomi app store
