### ISSUE TITLE
Success update not received by app for payments done after performing App Store Verifications on iOS

### ISSUE THREAD

**Issue by faizan-winjit** [dooboolab-community/flutter_inapp_purchase#474]
We are currently facing a challenging issue with the flutter_inapp_purchase package, specifically related to iOS and the handling of in-app purchases with additional verifications through the App Store.

Problem Description: When users attempt to make a purchase on iOS, they are sometimes prompted to move to the App Store to perform additional verifications (e.g., Credit Card expiration, adding UPI account/ID, entering two-factor code, parental control, etc.). During this process, our listeners receive a failed transaction update as soon as the user clicks on "Go to App Store." Subsequently, even if the user completes the verifications in the App Store (such as adding UPI ID, entering a two-factor authentication code, etc.) and makes the payment, our app never receives a SUCCESS update, and the promised reward is not provided to the user. So the money is deducted from the users account, but the user never receives the promised reward. 

**Additional Context:**
•	The issue occurs only on the live app downloaded from the App Store.
•	We are unable to replicate the problem in the sandbox, as in the sandbox environment, the user is not required to leave the app to make a purchase.

**Steps Taken:**
•	We have implemented the flutter_inapp_purchase package for handling consumable products.
•	The issue is specific to iOS and is not encountered on Android.
**Request for Help:** We are reaching out to the Flutter community for assistance in resolving this issue. If anyone has encountered a similar problem or has insights into the underlying mechanisms causing failed transactions during App Store verifications, your expertise would be highly appreciated.

**Questions:**
1.	Has anyone experienced a similar issue with the flutter_inapp_purchase package on iOS?
2.	Are there specific considerations or configurations we might be missing related to handling in-app purchases on iOS with additional verifications?

**Package Version:**
•	flutter_inapp_purchase: 5.4.2

Any guidance, suggestions, or insights you can provide would be immensely helpful in resolving this issue and ensuring a seamless in-app purchase experience for our users.

Thank you in advance for your time and assistance!

**Comment by arsarsars1** [comment]
I can relate to the issue you're facing, and I'm currently encountering a similar challenge with Apple subscriptions. Due to this, I've been unable to deploy the application. Do you happen to know which older version was working fine? Thank you for your help.

**Comment by arsarsars1** [comment]
Is there's any update on the issue seems like still it is not working.
