### ISSUE TITLE
 FlutterInappPurchase.purchaseUpdated don't work for subscription

### ISSUE THREAD

**Issue by KyawSoeW1n** [dooboolab-community/flutter_inapp_purchase#483]
flutter_inapp_purchase: ^5.6.1

(iOS)

Expected behavior - FlutterInappPurchase.purchaseUpdated listener work for subscription is success.
Actual behavior -  FlutterInappPurchase.purchaseUpdated listener don't work even subscription is success.

Tested environment  - Simulator

Steps to reproduce the behavior - Make a subscription and wait for result.

**Comment by anilthummar** [comment]
@KyawSoeW1n @arisbartee @LinusU @emostar @nucleartux 
Why my payment not work in ios device ,
Always  getting CANCEL keyword,

purchaseErrorSubscription = FlutterInappPurchase.purchaseError.listen((purchaseError) {
      debugPrint('purchase-error: ${purchaseError?.code}');
      
      So using this code getting close my transaction process, Please help me

**Comment by KyawSoeW1n** [comment]
You have to make product id in apple store and use that id to purchase or subscription. For me , stream are not working. But payment is success.

**Comment by KyawSoeW1n** [comment]
@anilthummar only FlutterInappPurchase.connectionUpdated and FlutterInappPurchase.purchaseUpdated are not working.
