### ISSUE TITLE
iOS flutter_inapp_purchase in ios geting error listen (FlutterInappPurchase.purchaseError) 

### ISSUE THREAD

**Issue by anilthummar** [dooboolab-community/flutter_inapp_purchase#486]
@arisbartee @LinusU @emostar @nucleartux 

Please help me for same.

### Version of flutter_inapp_purchase
flutter_inapp_purchase: ^5.6.1

### Platforms where the error occurred (iOS)
The error occurred on iOS only.

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
When initiating my payment process using the following code:
1. `await FlutterInappPurchase.instance.initialize();`
2. `connectionSubscription = FlutterInappPurchase.connectionUpdated.listen((connected) { print("test") });`
3. `purchaseUpdatedSubscription = FlutterInappPurchase.purchaseUpdated.listen((productItem) async) { print("test") });`
4. `purchaseErrorSubscription = FlutterInappPurchase.purchaseError.listen((purchaseError) { print("test") });`

I encounter an error at the 4th step. Every time the control reaches the 4th step, my payment process halts, but this issue occurs only on iOS.

**Comment by KyawSoeW1n** [comment]
Is it work on emulator?

**Comment by anilthummar** [comment]
@KyawSoeW1n  not its not work on emulator , i have check and test in real iPhone device
